language: scala
scala:
   - 2.11.5
jdk:
  - oraclejdk8
matrix:
  fast_finish: true
notifications:
  email: false
script:
  - travis_retry sbt compile
  - sbt -DspanScaleFactor=5.0 coverage test
after_success:
  - sbt coveralls