language: scala
scala:
   - 2.11.7
jdk:
  - oraclejdk8
matrix:
  fast_finish: true
notifications:
  email: false
script:
  - travis_retry sbt compile
  - sbt -DspanScaleFactor=5.0 coverage test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
  - sbt coveralls